export const jobDetailsData = [
    {
      jobDescription: {
        jobTitle: "Senior SAP FICO Consultant",
        location: "Coimbatore",
        terms: "Full Time",
        expirence: "10 years",
        remuneration: "Market Standard",
      },
      aboutUs:
        "Hub-AI is an SAP S/4HANA consulting company, fast-growing with over 150+ consultants, and has 100% YOY growth. Our vibrant and diverse culture builds an environment where collaboration and innovation thrive. We prioritize providing plenty of opportunities for learning and professional development, ensuring every team member can plan their path to success along with the company's progressive growth. This unique blend of growth, culture, and career development makes us a top choice in the SAP consulting field.",
      aboutTheRole:
        "The Consultant facilitates the implementation and support of SAP Finance and controlling to enhance the client's business functionality and overall performance while maintaining a high degree of customer satisfaction.",
      responsibilities: [
        "Candidate should know SAP implementation methodology i.e. ASAP and Active Methodology.",
        "Design, configuration, and testing of core FI/CO modules (GL, New GL functionality, AP, AR).",
        "Design, configuration, and testing of Asset Management.",
        "Design, configuration, and testing of Consolidations.",
        "Design, configuration, and testing of CO-PA.",
        "Design, configuration, and testing of Cost center accounting.",
        "Design, configuration, and testing of Profit center accounting.",
        "Design, configuration, and testing of Product costing.",
        "Design, configuration, and testing of the Material ledger.",
        "Experience and knowledge of key integration points with FI/CO modules.",
        "Ability to configure FICO processes in S/4HANA and should have knowledge of simplification in the FICO module.",
        "Deep knowledge of FICO Enterprise structure, Business partner, FSCM, New GL functionality, Material ledger, Taxation, Banking automation, Logistics integrated accounting entries.",
      ],
      candidateRequirements: [
        "Bachelor's Degree (Preferably in Finance / Accounting).",
        "Minimum 10 years of SAP FI/CO configuration experience.",
        "Should have four full lifecycle SAP implementation experiences (Project Preparation through Go-Live and Hyper care) and at least 2 full lifecycle S/4HANA greenfield implementations.",
        "Strong knowledge of Taxation, P&L, and Balance sheet.",
        "Business knowledge and process design skills.",
        "Ability to analyze problems and provide clear recommendations.",
        "Strong organizational skills.",
        "Able to collaborate with clients and have a strong desire to excel.",
        "Excellent communication skills, written and verbal.",
        "Good interpersonal skills.",
        "Must be able to work independently as well as a team player and can manage own workload.",
      ],
    },
    {
      jobDescription: {
        jobTitle: "Senior Cold Call Specialist",
        location: "Coimbatore",
        terms: "Full Time",
        expirence: "10 years",
        remuneration: "Market Standard",
      },
      aboutUs:
        "Hub-AI is an SAP S/4HANA consulting company, fast-growing with over 150+ consultants, and has 100% YOY growth. Our vibrant and diverse culture builds an environment where collaboration and innovation thrive. We prioritize providing plenty of opportunities for learning and professional development, ensuring every team member can plan their path to success along with the company's progressive growth. This unique blend of growth, culture, and career development makes us a top choice in the SAP consulting field.",
      aboutTheRole:
        "The Consultant facilitates the implementation and support of SAP Finance and controlling to enhance the client's business functionality and overall performance while maintaining a high degree of customer satisfaction.",
      responsibilities: [
        "Candidate should know SAP implementation methodology i.e. ASAP and Active Methodology.",
        "Design, configuration, and testing of core FI/CO modules (GL, New GL functionality, AP, AR).",
        "Design, configuration, and testing of Asset Management.",
        "Design, configuration, and testing of Consolidations.",
        "Design, configuration, and testing of CO-PA.",
        "Design, configuration, and testing of Cost center accounting.",
        "Design, configuration, and testing of Profit center accounting.",
        "Design, configuration, and testing of Product costing.",
        "Design, configuration, and testing of the Material ledger.",
        "Experience and knowledge of key integration points with FI/CO modules.",
        "Ability to configure FICO processes in S/4HANA and should have knowledge of simplification in the FICO module.",
        "Deep knowledge of FICO Enterprise structure, Business partner, FSCM, New GL functionality, Material ledger, Taxation, Banking automation, Logistics integrated accounting entries.",
      ],
      candidateRequirements: [
        "Bachelor's Degree (Preferably in Finance / Accounting).",
        "Minimum 10 years of SAP FI/CO configuration experience.",
        "Should have four full lifecycle SAP implementation experiences (Project Preparation through Go-Live and Hyper care) and at least 2 full lifecycle S/4HANA greenfield implementations.",
        "Strong knowledge of Taxation, P&L, and Balance sheet.",
        "Business knowledge and process design skills.",
        "Ability to analyze problems and provide clear recommendations.",
        "Strong organizational skills.",
        "Able to collaborate with clients and have a strong desire to excel.",
        "Excellent communication skills, written and verbal.",
        "Good interpersonal skills.",
        "Must be able to work independently as well as a team player and can manage own workload.",
      ],
    },
    {
      jobDescription: {
        jobTitle: "Senior Business Development Manager",
        location: "Coimbatore",
        terms: "Full Time",
        expirence: "10 years",
        remuneration: "Market Standard",
      },
      aboutUs:
        "Hub-AI is an SAP S/4HANA consulting company, fast-growing with over 150+ consultants, and has 100% YOY growth. Our vibrant and diverse culture builds an environment where collaboration and innovation thrive. We prioritize providing plenty of opportunities for learning and professional development, ensuring every team member can plan their path to success along with the company's progressive growth. This unique blend of growth, culture, and career development makes us a top choice in the SAP consulting field.",
      aboutTheRole:
        "The Consultant facilitates the implementation and support of SAP Finance and controlling to enhance the client's business functionality and overall performance while maintaining a high degree of customer satisfaction.",
      responsibilities: [
        "Candidate should know SAP implementation methodology i.e. ASAP and Active Methodology.",
        "Design, configuration, and testing of core FI/CO modules (GL, New GL functionality, AP, AR).",
        "Design, configuration, and testing of Asset Management.",
        "Design, configuration, and testing of Consolidations.",
        "Design, configuration, and testing of CO-PA.",
        "Design, configuration, and testing of Cost center accounting.",
        "Design, configuration, and testing of Profit center accounting.",
        "Design, configuration, and testing of Product costing.",
        "Design, configuration, and testing of the Material ledger.",
        "Experience and knowledge of key integration points with FI/CO modules.",
        "Ability to configure FICO processes in S/4HANA and should have knowledge of simplification in the FICO module.",
        "Deep knowledge of FICO Enterprise structure, Business partner, FSCM, New GL functionality, Material ledger, Taxation, Banking automation, Logistics integrated accounting entries.",
      ],
      candidateRequirements: [
        "Bachelor's Degree (Preferably in Finance / Accounting).",
        "Minimum 10 years of SAP FI/CO configuration experience.",
        "Should have four full lifecycle SAP implementation experiences (Project Preparation through Go-Live and Hyper care) and at least 2 full lifecycle S/4HANA greenfield implementations.",
        "Strong knowledge of Taxation, P&L, and Balance sheet.",
        "Business knowledge and process design skills.",
        "Ability to analyze problems and provide clear recommendations.",
        "Strong organizational skills.",
        "Able to collaborate with clients and have a strong desire to excel.",
        "Excellent communication skills, written and verbal.",
        "Good interpersonal skills.",
        "Must be able to work independently as well as a team player and can manage own workload.",
      ],
    },
  ];